# Generated by Django 5.2 on 2025-04-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Mid', 'Mid'), ('Low', 'Low')], default='MID', max_length=4),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Blocked', 'Blocked')], default='Pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='Assignee',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='TaskPriority',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
