# Generated by Django 5.2 on 2025-04-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_todo_assignee_remove_todo_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Mid', 'Mid'), ('Low', 'Low')], default='Mid', max_length=4),
        ),
    ]
